<a href="https://colab.research.google.com/github/ANAMIKA1410/Twitter-Sentiment-Analysis-informal/blob/main/Minor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sentimental Analysis : MINOR PROJECT

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string

# Loading Data

In [ ]:
df1 = pd.read_csv("https://raw.githubusercontent.com/ANAMIKA1410/Twitter-Sentiment-Analysis-informal/main/Anamika/data/data/marrrcin.csv",encoding='latin-1')
df2 = pd.read_csv("https://raw.githubusercontent.com/ANAMIKA1410/Twitter-Sentiment-Analysis-informal/main/Anamika/data/data/Joseph-Ndungi.csv")
df3 = pd.read_csv("https://raw.githubusercontent.com/utquarsh027/Twitter-Sentiment-Analysis-informal/main/Anamika/data/data/d1.csv",encoding='latin-1')
df4 = pd.read_csv("https://raw.githubusercontent.com/utquarsh027/Twitter-Sentiment-Analysis-informal/main/Anamika/data/data/prateekjoshi565.csv")
!pip install opendatasets
import opendatasets as od
dataset_url ='https://www.kaggle.com/datasets/kazanova/sentiment140'
od.download(dataset_url)
import os
data_dir='./sentiment140'
os.listdir(data_dir)
train_csv=data_dir + '/training.1600000.processed.noemoticon.csv'
df8=pd.read_csv(train_csv,encoding='ISO-8859-1')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: opendatasets in /usr/local/lib/python3.8/dist-packages (0.1.22)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from opendatasets) (7.1.2)
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (from opendatasets) (1.5.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from opendatasets) (4.64.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (2.25.1)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (8.0.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (1.24.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle->opendatasets) (2022.12.7)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle->opendatasets) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle->opendatasets) (2.10)
Skipping, found downloaded files in "./sentiment140" (use force=True to force download)

Df1

In [ ]:
df_list=[df1,df2,df3,df4,df8]
df1=df1[['Category']]
df1.dropna(inplace=True)
df1=df1[df1['Category']!='Not Available']
df1.rename(columns={'Category':'tweets'},inplace=True)
#df2
df2=df2[['text']]
df2.rename(columns={'text':'tweets'},inplace=True)
#df3
df3.rename(columns={'message to examine':'tweets'},inplace=True)
df3=df3[['tweets']]
df3.dropna(inplace=True)
#df4
df4=df4[['tweet']]
df4.rename(columns={'tweet':'tweets'},inplace=True)
#df8
df8.columns=['1','2','3','4','5','6']
df8=df8[['6']]
df8.rename(columns={'6':'tweets'},inplace=True)


df_list = [df1,df2,df3]

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

# Preprocessing



> In the following peice of code, extraction of english words is carried out:
* As this project mainly focuses on english language tweet thus extracting only english words and getting rid of unnecessary characters.

In [ ]:
mylist =["Do you like my pokemon? ü•∫üíï \n#ÊàêÈÉΩÂêåÂüé #ÊàêÈÉΩËµÑÊ∫ê #ÊàêÈÉΩ ","@jk cdbsa jf"]
def english_only(tweets):

  alpha = (list(string.ascii_letters))
  valid = []
  final = []
  for i in alpha :
    valid.append(i)
  for i in range(0,10):
    valid.append(str(i))
  symbols = ['!','?','.','@','#','"',',',"'",'/',':','(',')']
  for i in symbols:
    valid.append(i)

  def replace(l,v):
    m =[]

    for i in l:
      for j in i:
        if j not in valid:
          i = i.replace(j," ")
      m.append(i)
    return m

  final = replace(tweets,valid)
  return final


  def spaceremoval(tweets):
    new_lst = []
    pattern=re.compile(r'# +')
    for i in tweets:
        i=re.sub(pattern,"",i)
        new_lst.append(i)
    return new_lst  
  final_1 = spaceremoval(final)

df2["tweets"] = english_only(df2["tweets"])
df2

,tweets,hashtags,mentions
0,@CBCNews Stupid Canadians jumping up to defend...,[],[@CBCNews]
1,The misty rain on the painted bridge spa spa ...,[],[]
2,To love beauty is to see light. https://t.co/c...,[],[]
3,how are you?! me: https://t.co/33r0ouu59L,[],[]
4,Do you like my pokemon? https://t.co/ck97A...,[],[]
...,...,...,...
995,@AltTextUtil @oedipusnj Extracted text in imag...,[],"[@AltTextUtil, @oedipusnj]"
996,If a relationship is founded o. https://t.co/E...,[],[]
997,This dude is dangerous. He'll do anything or l...,[],[]
998,"I like you,like it all over the mountains ...",[],[]
999,"""I am horribly sick of dress!"" joi https://t....",[],[]



> In the following peice  of code all the hashtags and mentions are extracted and fed in to a new column.

In [ ]:
def find_hashtags(tweet):
    #This function extracts hashtags from the tweets.
    return re.findall('(#[A-Za-z]+[A-Za-z0-9-_]+)', tweet) 

def find_mentions(tweet):
    #This function extracts hashtags from the tweets.
    return  re.findall('(@[A-Za-z]+[A-Za-z0-9-_]+)', tweet)
    
df1['hashtags']  = df1.tweets.apply(find_hashtags)
df1['mentions']  = df1.tweets.apply(find_mentions)
#= df1.tweets.apply(find_hashtags)
df1

for i in df_list :
  i['hashtags']  = i.tweets.apply(find_hashtags)
  i['mentions']  = i.tweets.apply(find_mentions)

df2

,tweets,hashtags,mentions
0,@CBCNews Stupid Canadians jumping up to defend...,[],[@CBCNews]
1,The misty rain on the painted bridge spa spa ...,[],[]
2,To love beauty is to see light. https://t.co/c...,[],[]
3,how are you?! me: https://t.co/33r0ouu59L,[],[]
4,Do you like my pokemon? https://t.co/ck97A...,[],[]
...,...,...,...
995,@AltTextUtil @oedipusnj Extracted text in imag...,[],"[@AltTextUtil, @oedipusnj]"
996,If a relationship is founded o. https://t.co/E...,[],[]
997,This dude is dangerous. He'll do anything or l...,[],[]
998,"I like you,like it all over the mountains ...",[],[]
999,"""I am horribly sick of dress!"" joi https://t....",[],[]

In [ ]:
lst=["DO you #like my pokemon? # # # https//google.com","hey whatsappn # # # dgdgd #whatsapp"]

def spaceremoval(tweets):
    new_lst = []
    pattern=re.compile(r'# +')
    for i in tweets:
        i=re.sub(pattern,"",i)
        new_lst.append(i)
    return new_lst
df2["tweets"] = spaceremoval(df2["tweets"])

In [ ]:
df2

,tweets,hashtags,mentions
0,@CBCNews Stupid Canadians jumping up to defend...,[],[@CBCNews]
1,The misty rain on the painted bridge spa spa ...,[],[]
2,To love beauty is to see light. https://t.co/c...,[],[]
3,how are you?! me: https://t.co/33r0ouu59L,[],[]
4,Do you like my pokemon? https://t.co/ck97A...,[],[]
...,...,...,...
995,@AltTextUtil @oedipusnj Extracted text in imag...,[],"[@AltTextUtil, @oedipusnj]"
996,If a relationship is founded o. https://t.co/E...,[],[]
997,This dude is dangerous. He'll do anything or l...,[],[]
998,"I like you,like it all over the mountains ...",[],[]
999,"""I am horribly sick of dress!"" joi https://t....",[],[]